from __future__ import annotations

from datetime import datetime
from typing import Generic, TypeVar, Literal

from pydantic import BaseModel, Field, ConfigDict

T = TypeVar("T")


class APIModel(BaseModel):
    # strict: no unrecognized fields allowed
    model_config = ConfigDict(extra="forbid")


class Meta(APIModel):
    generated_at: datetime = Field(..., description="When this payload was generated by the cache builder/ingestor")
    source: Literal["redis"] = "redis"
    ttl_seconds: int | None = Field(default=None, description="TTL remaining/assigned when written")


class ListResponse(APIModel, Generic[T]):
    data: list[T]
    meta: Meta
